FROM python:3.9

RUN apt-get update && apt-get install -y wget build-essential gmsh openssh-server
RUN cd /tmp \
    && wget https://github.com/apptainer/apptainer/releases/download/v1.2.5/apptainer_1.2.5_amd64.deb \
    && apt-get install -y ./apptainer_1.2.5_amd64.deb \
    && rm /tmp/*

WORKDIR /
RUN wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.6.tar.gz
RUN tar zxvf openmpi-4.1.6.tar.gz
WORKDIR /openmpi-4.1.6
RUN ./configure --prefix=/opt/openmpi/4.1.6
RUN make all
RUN make install
RUN ldconfig

WORKDIR /
RUN wget https://download.open-mpi.org/release/open-mpi/v1.10/openmpi-1.10.6.tar.gz
RUN tar -xzvf openmpi-1.10.6.tar.gz
WORKDIR /openmpi-1.10.6
RUN ./configure --prefix=/opt/openmpi/1.10.6
RUN make all
RUN make install
RUN ldconfig

RUN sed -i '/^#PermitRootLogin/s/#//' /etc/ssh/sshd_config
RUN sed -i '/^PermitRootLogin/s/prohibit-password/yes/' /etc/ssh/sshd_config
RUN service ssh start

ARG SSH_DIR=/root/.ssh

COPY ./.dev-env-config/id_mpi $SSH_DIR/id_mpi
COPY ./.dev-env-config/id_mpi.pub $SSH_DIR/id_mpi.pub
COPY ./.dev-env-config/id_mpi.pub $SSH_DIR/authorized_keys

RUN chmod 0700 $SSH_DIR
RUN chmod 0644 $SSH_DIR/id_mpi.pub
RUN chmod 0600 $SSH_DIR/authorized_keys
RUN chmod 0600 $SSH_DIR/id_mpi
RUN (echo "Host *"; echo " IdentityFile ~/.ssh/id_mpi"; echo " StrictHostKeyChecking no"; echo "") > $SSH_DIR/config

# Install the package dependencies in the requirements file.
COPY /executer-tracker/requirements.txt /requirements.txt
RUN pip install --no-cache-dir --upgrade -r /requirements.txt

COPY /executer-tracker /executer-tracker
WORKDIR /executer-tracker
RUN pip install .

COPY ./common/events /common/events
RUN pip install --no-cache-dir --upgrade /common/events
COPY ./common/task_status /common/task_status
RUN pip install --no-cache-dir --upgrade /common/task_status

CMD ["bash", "-c", "service ssh start && python ./executer_tracker/main.py"]
