name: Build Docker image and push to Docker Hub

on:
  push:
    branches:
      - main
      - dev

    paths:
      - 'common/**'
      - 'task-runner/**'
      - 'file-tracker/**'

jobs:
  build-publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            inductiva/task-runner
            inductiva/file-tracker
          # generate Docker tags based on the branch
          tags: |
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

          labels: |
            org.opencontainers.image.url=https://inductiva.ai/
            org.opencontainers.image.source=${{ github.repository }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push task-runner to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./task-runner/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.title=Task Runner
            org.opencontainers.image.description=Task runner for the Inductiva API

      - name: Build and push file-tracker to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./file-tracker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            org.opencontainers.image.title=File Tracker
            org.opencontainers.image.description=File tracker for the Inductiva API

